import React, { Component } from "react";
import { Link } from "react-router-dom";
import PropTypes from "prop-types";
import { connect } from "react-redux";
import { loginUser } from "../../actions/authActions";
import classnames from "classnames";
import Avatar from "@material-ui/core/Avatar";
import LockOutlinedIcon from "@material-ui/icons/LockOutlined";
import Typography from "@material-ui/core/Typography";
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import { Container, Card, CardContent } from "@material-ui/core";
import Navbar from "../../components/layout/Navbar";
import loveLeft from "../../assets/images/love.gif";
import bg from "../../assets/images/login-bg.svg";
import loveRight from "../../assets/images/love-in-air.gif";

class TermsConditions extends Component {
	constructor() {
		super();
		this.state = {
			email: "",
			password: "",
			errors: {},
			showLoader: "none",
			showLogin: "yes",
			showMenu: "none",
		};
	}
	componentDidMount() {
		// If logged in and user navigates to Login page, should redirect them to dashboard
		if (this.props.auth.isAuthenticated) {
			this.props.history.push("/user/home");
		}
	}
	componentWillReceiveProps(nextProps) {
		if (nextProps.auth.isAuthenticated) {
			this.setState({ showLoader: "none" });
			this.props.history.push("/user/home"); // push user to dashboard when they login
		}
		if (nextProps.errors) {
			this.setState({ showLoader: "none" });
			this.setState({
				errors: nextProps.errors,
			});
		}
	}
	onChange = (e) => {
		this.setState({ [e.target.name]: e.target.value });
	};
	onSubmit = (e) => {
		e.preventDefault();
		if (this.state.email && this.state.password) {
			this.setState({ showLoader: "" });
		}
		const userData = {
			email: this.state.email,
			password: this.state.password,
		};
		this.props.loginUser(userData); // since we handle the redirect within our component, we don't need to pass in this.props.history as a parameter
	};
	render() {
		const { errors } = this.state;
		return (
			<div className='container' style={{
				height: "100%",
				paddingBottom:"3%",
				maxWidth: "inherit",
				position: "relative",
				// backgroundSize: "100%",
				// backgroundPosition: "100%",
				backgroundImage: "linear-gradient(#f3f3f3, rgb(255, 251, 255), rgb(229 213 213))",
				backgroundRepeat: "no-repeat",
			}}>
				<Navbar customProps={this.state} />
				<div
					style={{
						marginTop: "3%"
					}}
					className='row'>
					<Container maxWidth='lg'>
						<Card>
							<CardContent>
								<div style={{ padding: "2%" }}>
									<Typography align="center" variant="h4" style={{ color: "#c9293c", marginBottom: "2%" }} component="div">
										Terms of Service</Typography>
									<div style={{marginBottom: "2%"}}>
										<Typography variant="body2" style={{ color: "grey" }}>
											This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.
											<br></br><br></br>
											This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and the terms and conditions for access or usage of www.bharatmatrimony.com (the "Website").
											<br></br><br></br>
											PLEASE READ THE FOLLOWING TERMS AND CONDITIONS VERY CAREFULLY BEFORE USING THE WEBSITE. ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE IMPLIES YOUR AGREEMENT TO BE BOUND BY ALL THESE TERMS AND CONDITIONS ("Agreement"). If you do not want to be bound by the Terms and Conditions, you must not use the Website or the Vyvaha Services. The Terms and Conditions also includes the applicable policies which are incorporated herein by way of reference and as amended from time to time (the "Terms and conditions").
										</Typography>
									</div>
									<br></br>
									<div>
										<Typography align="left" variant="h5" style={{ color: "#c9293c", marginBottom: "1%" }} component="div">
											Eligibility</Typography>
										<Typography variant="body2" style={{ color: "grey", marginLeft: "2%" }}>
											<p style={{ marginBottom: "0.05%" }}>
												1. To register as a member of Vyvaha.com or use this Site, you must be legally competent and of legal marriageable age as per the laws of India (currently, 18 years or over for females and 21 years or over for males).
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												2. The Vyvaha.com site is only to facilitate personal advertisement for lawful marriage alliance between persons who are legally competent to enter into matrimony under the laws to which they are subject. Membership in the Service is void where prohibited.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												3. By using this Site, you represent and warrant that you have the right, consent, authority, and legal capacity to enter into this Agreement; submit relevant information to us; and that you are not prohibited or prevented by any applicable law for the time being in force or any order or decree or injunction from any court, tribunal or any such competent authority restraining you from entering into matrimony.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												4. You further confirm that you, intent to seek a life partner and that you shall not use this site for casual dating. You also agree to abide by all of the terms and conditions of this Agreement. If at any time Vyvaha.com is of the opinion (in its sole discretion) or has any reason to believe that you are not eligible to become a member or that you have made any misrepresentation, Vyvaha.com reserves the right to forthwith terminate your membership and / or your right to use the Service without any refund to you of any of your unutilized subscription fee.
											</p>
										</Typography>
									</div>
									<br></br>
									<div>
										<Typography align="left" variant="h5" style={{ color: "#c9293c", marginBottom: "1%" }} component="div">
											Account Security</Typography>
										<Typography variant="body2" style={{ color: "grey"}}>
											<p style={{ marginBottom: "0.05%" }}>
												You are responsible for maintaining the confidentiality of your login credentials you designate during the registration process, and you are solely responsible for all activities that occur under your account. You agree to immediately notify us of any disclosure or unauthorized use of your account or any other breach of security, and ensure that you log out from your account at the end of each session.
											</p>
											<br></br>
										</Typography>
									</div>
									<br></br>
									<div>
										<Typography align="left" variant="h5" style={{ color: "#c9293c", marginBottom: "1%" }} component="div">
											Term and Termination</Typography>
										<Typography variant="body2" style={{ color: "grey", marginLeft: "2%" }}>
											<p style={{ marginBottom: "0.05%" }}>
												1. This Agreement will be effective, valid and subsisting as long as you use our Site.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												2. You may terminate your membership at any time, for any reason by writing to Vyvaha.com. In the event you terminate your membership, you will not be entitled to a refund of any unutilized subscription fees, if any, paid by you, except where otherwise guaranteed in writing.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												3. Vyvaha.com may terminate your access to the Site and/or your membership for any reason including but not limited to breach of the terms of use, using the service for commercial purpose, engaging in prohibited or inappropriate communication or activity, by sending notice to you at the email address as provided by you in your application for membership or such other email address as you may later provide to Vyvaha.com. If Vyvaha.com terminates your membership for breach of terms of this Agreement, you will not be entitled to any refund of any Subscription fees, if any, paid by you.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												4. Certain provisions of this Agreement including sections 4, 5, 6, 7 and sections 9 to 16, of this Agreement shall remain effective even on termination.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												5. Term for the paid Membership would be in accordance with the type of membership undertaken.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												6. In the event of business discontinuity, the Company shall refund 50% of the unused membership fees paid by you.
											</p>
										</Typography>
									</div>
									<br></br>
									<div>
										<Typography align="left" variant="h5" style={{ color: "#c9293c", marginBottom: "1%" }} component="div">
										Non-Commercial Use by Members.</Typography>
										<Typography variant="body2" style={{ color: "grey"}}>
											<p style={{ marginBottom: "0.05%" }}>
											The Site is for the personal use of individual members to advertise and promote their profiles for the purpose of generating accepts from relevant matches and cannot be used in connection with any commercial endeavors. This includes providing links to other web sites, whether deemed competitive to Vyvaha.com or otherwise. Organizations, companies, and/or businesses cannot become Members of Vyvaha.com and should not use the Vyvaha.com Service or Site for any purpose. Illegal and/or unauthorized uses of the Site, including unauthorized framing of or linking to the Site will be investigated, and appropriate legal action will be taken, including without limitation, civil, criminal, and injunctive redress.
											</p>
											<br></br>
										</Typography>
									</div>
									<br></br>
									<div>
										<Typography align="left" variant="h5" style={{ color: "#c9293c", marginBottom: "1%" }} component="div">
											Other Terms of Use for Members</Typography>
										<Typography variant="body2" style={{ color: "grey", marginLeft: "2%" }}>
											<p style={{ marginBottom: "0.05%" }}>
												1. Vyvaha.com reserves the right in it's sole discretion to review the activity and status of each account and block access to the member based on such review.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												2. Vyvaha.com reserve the right at its sole discretion to restrict/suspend your free access to its website based on review of the member's activity, status or any such criteria Vyvaha.com may deems fit and proper with due intimation to you.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												3. You hereby confirm that as on date of this registration, you do not have any objection to receive emails, SMS/WhatsApp messages and calls from Vyvaha.com and members of Vyvaha.com as long as you are a registered member of Vyvaha.com including SMS permission for authenticating mobile verification wand transactions via OTP, sent by the Payment Gateway. This consent shall supersede any preferences set by you with or registration done with the Do Not Disturb (DND Register)/ National Customer Preference Register (NCPR). This consent extends to emails, messages or calls relating but not limited to phone number verification, the provision of matchmaking advertising service, matchmaking enquiries and promotions.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												4. Multiple profiles of the same person are not allowed on our Site. Vyvaha.com reserves the right to deactivate all multiple profiles without any refund of subscription fees.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												5. You confirm that the Content, information including the personal information provided by you is correct and accurate.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												6. You are strongly advised to submit copy of your Driving License, Passport or any other Government issued identity and add a trust badge to your profile.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												7. Except for the purpose of promoting/advertising your profile for matchmaking purposes, you cannot engage in advertising to, or solicitation of, other Members to buy or sell any products or services through the Service.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												8. You will not transmit any chain letters or junk email to other Vyvaha.com Members. Although Vyvaha.com cannot monitor the conduct of its Members off the Vyvaha.com Site, it is also a violation of these rules to use any information obtained from other members in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to any Member without their prior explicit consent.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												9. Vyvaha.com reserves the right to take appropriate steps to protect Vyvaha.com and/or its Members from any abuse/misuse as it deems appropriate in its sole discretion.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												10. You cannot use any automated processes, including IRC Bots, EXE's, CGI or any other programs/scripts to view content on or communicate / contact / respond / interact with Vyvaha.com and/or its members.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												11. Vyvaha.com reserves the right to screen communications/advertisements that you may send to other Member(s) and also regulate the same by deleting unwarranted/obscene communications/advertisements at any time at its sole discretion without prior notice to any Member.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												12. Vyvaha.com Members who subscribe to the Vyvaha.com Select Service hereby, unconditionally and irrevocably confirm that you have read terms and conditions and agree to abide by them.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												13. Under this license you may not: Attempt to decompile or reverse engineer any software contained on VedicAstroAPI's web site or API. Access the Site or Services in order to build a similar or competitive service. This license shall automatically terminate if you violate any of these restrictions and may be terminated by VedicAstroAPI at any time.
											</p>
										</Typography>
									</div>
									<br></br>
									<div>
										<Typography align="left" variant="h5" style={{ color: "#c9293c", marginBottom: "1%" }} component="div">
										Proprietary Rights in the Content on Vyvaha.com</Typography>
										<Typography variant="body2" style={{ color: "grey"}}>
											<p style={{ marginBottom: "0.05%" }}>
											Vyvaha.com owns and retains all proprietary rights in the Vyvaha.com Site and the Vyvaha.com Service. The Site contains the copyrighted material, trademarks, and other proprietary information of Vyvaha.com, and its licensors. Except for that information which is in the public domain such as member profile or for which permission has been obtained from the user, you cannot copy, modify, publish, transmit, distribute, perform, display, or sell any such proprietary information. Any such act or an attempted act on your part shall constitute a violation of this Agreement and your membership is liable to be terminated forthwith by Vyvaha.com without refund of any of your unused Subscription fees. Vyvaha.com reserves right to take legal action (civil and/or criminal) wherever applicable for any violations.
											</p>
											<br></br>
										</Typography>
									</div>
									<br></br>
									<div>
										<Typography align="left" variant="h5" style={{ color: "#c9293c", marginBottom: "1%" }} component="div">
										Content Posted on the Site</Typography>
										<Typography variant="body2" style={{ color: "grey"}}>
											<p style={{ marginBottom: "0.05%" }}>
											The following is an indicative list of the kind of Content that is illegal or prohibited on the Site. Vyvaha.com will investigate and take appropriate legal action in its sole discretion against anyone who violates this Agreement, including without limitation, removing the offending communication/Content from the Service and terminating the Membership of such violators without a refund. Illegal and prohibitive Content includes Content which:
											</p>
											<br></br>
										</Typography>
										<Typography variant="body2" style={{ color: "grey", marginLeft: "2%" }}>
											<p style={{ marginBottom: "0.05%" }}>
												1. Is blatantly offensive to the community, such as Content that promotes racism, bigotry, hatred or physical harm of any kind against any group or individual;
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												2. Harasses or advocates harassment of another person;
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												3. Involves the transmission of "junk mail", "chain letters," or unsolicited mass mailing or "spamming";
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												4. Promotes information that you know is false, misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												5. Promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												6. Contains restricted or password only access pages, or hidden pages or images (those not linked to or from another accessible page);
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												7. Displays pornographic or sexually explicit material of any kind;
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												8. Provides material that exploits people under the age of 18 in a sexual or violent manner, or solicits personal information from anyone under 18;
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												9. Provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												10. Solicits passwords or personal identifying information for commercial or unlawful purposes from other users; and
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												11. Engages in commercial activities and/or sales without our prior written consent such as contests, sweepstakes, barter, advertising, and pyramid schemes
											</p>
										</Typography>
									</div>
									<br></br>
									<div>
										<Typography align="left" variant="h5" style={{ color: "#c9293c", marginBottom: "1%" }} component="div">
											Disclaimers</Typography>
										<Typography variant="body2" style={{ color: "grey", marginLeft: "2%" }}>
											<p style={{ marginBottom: "0.05%" }}>
												1. Vyvaha.com is not responsible for any incorrect or inaccurate Content/listing posted on the Site or in connection with the Vyvaha.com Service, whether caused by Users, Members or by any of the equipment or programming associated with or utilized in the Service, nor for the conduct of any User and/or Member of the Vyvaha.com Service whether online or offline.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												2. Vyvaha.com assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, User and/or Member communications or any communications by Vyvaha.com to its Members.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												3. Vyvaha.com is not responsible for any problems or technical malfunction of any telephone network or lines, computer on-line-systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any web site or combination thereof, including injury or damage to Users and/or Members or to any other person's computer related to or resulting and/or in connection with the Vyvaha.com Service.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												4. Under no circumstances will Vyvaha.com be responsible for any loss or damage resulting from anyone's use of the Site or the Service and/or any Content posted on the Vyvaha.com Site or transmitted to Vyvaha.com Members. You should not provide your financial information (for example, your credit card or bank account information), or wire or otherwise send money, to other Members.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												5. The exchange of matchmaking profile(s) through or by "Vyvaha.com" is not a matrimonial offer and/or recommendation from/by Vyvaha.com. Vyvaha.com shall not be responsible for any loss or damage to any individual arising out of, or subsequent to, any relations (including but not limited to matrimonial relations) established pursuant to the use of Vyvaha.com service.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												6. The Site and the Service are provided "AS-IS" and Vyvaha.com expressly disclaims any warranty of fitness for a particular purpose or non-infringement. Vyvaha.com cannot guarantee and does not promise any specific results from use of the Site and/or the Vyvaha.com Service. You understand that vyvaha.com makes no guarantees, either express or implied, regarding compatibility with individuals you meet through the Service.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												7. Vyvaha.com expressly disclaims any liability or responsibility whatsoever and howsoever arising as a result of any Content/listing posted on the Site / made available to Vyvaha.com by any Members or the users of the Site or any third party.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												8. Vyvaha.com does not assume any responsibility or liability for any illegal Content posted on the Site by any Members, users or any third party.
											</p>
											<br></br>
											<p style={{ marginBottom: "0.05%" }}>
												9. All liability, whether civil or criminal arising out of any Content that is Posted on the Site will be of that Member / user / third party who has Posted such Content and Vyvaha.com reserves its right to claim damages from such Member/ user / third party that it may suffer as a result of such Content Posted on the Site. Vyvaha.com does not claim ownership of Content you submit or make available for inclusion on the Service.
											</p>
										</Typography>
									</div>
									<br></br><br></br>
									<div style={{marginBottom: "2%"}}>
										<Typography variant="body2" style={{ color: "grey" }}>
											By becoming a member of Vyvaha.com and/or using the Services of the Site, you unconditionally and irrevocably confirm that you have read and understood the above provisions and agree to abide by them. If you are not agreeing to any of the above terms and conditions please refrain yourself from registering on the Site.
											<br></br><br></br>
											This Agreement is an electronic document in terms of the Information Technology Act, 2000 and Rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.
										</Typography>
									</div>
								</div>
							</CardContent>
						</Card>
					</Container>
				</div>
			</div>
		);
	}
}
TermsConditions.propTypes = {
	loginUser: PropTypes.func.isRequired,
	auth: PropTypes.object.isRequired,
	errors: PropTypes.object.isRequired,
};
const mapStateToProps = (state) => ({
	auth: state.auth,
	errors: state.errors,
});
export default connect(mapStateToProps, { loginUser })(TermsConditions);
